broker: sensorwebdata.engr.uga.edu
#sensorweb.us
port: 8883
#1883
topic_mapping: 
  # geophone: 
  #   database: shake
  #   db_table: Z
  #   dataname: value
  # batter_volt: 
  #   database: shake
  #   db_table: batvol
  #   dataname: value
  # usb_volt: 
  #   database: shake
  #   db_table: usbvol
  #   dataname: value  
  #topic for SmartPowerPlug
  Voltage:
    database: waveform
    #shake
    db_table: Voltage
    dataname: value 
  Current:
    database: waveform
    #shake
    db_table: Current
    dataname: value 
  Power:
    database: waveform
    #shake
    db_table: Power
    dataname: value 
  Reactive_Power:
    database: waveform
    #shake
    db_table: Reactive_Power
    dataname: value 
  Apparent_Power:
    database: waveform
    #shake
    db_table: Apparent_Power
    dataname: value 
  Power_Factor:
    database: waveform
    #shake
    db_table: Power_Factor
    dataname: value 
  # waveform_Voltage:
  #   database: shake
  #   db_table: waveform_Voltage
  #   dataname: value 
  # waveform_Current:
  #   database: shake
  #   db_table: waveform_Current
  #   dataname: value 
  Volt_THD:
    database: waveform
    #shake
    db_table: Volt_THD
    dataname: value 
  Curr_THD:
    database: waveform
    #shake
    db_table: Curr_THD
    dataname: value 
  Volt_Fund:
    database: waveform
    #shake
    db_table: Volt_Fund
    dataname: value 
  Curr_Fund:
    database: waveform
    #shake
    db_table: Curr_Fund
    dataname: value 
  Power_Energy_Acc:
    database: waveform
    #shake
    db_table: Power_Energy_Acc
    dataname: value 
  Reactive_Energy_Acc:
    database: waveform
    #shake
    db_table: Reactive_Energy_Acc
    dataname: value 
  temperature:
    database: waveform
    #shake
    db_table: temperature
    dataname: value 
influx_ip: sensorwebdata.engr.uga.edu
#sensorweb.us 
influx_user: smartplug
#algtest
influx_pass: joint@122
#sensorweb711
